### PR TITLE
Register handler

### LINKED ISSUE #127: [Frontend | Login Activities] User View Interactor

### PR DESCRIPTION
**Pull request by Jacob4649**
Closes #127, #125. 

- Adds a handler for registering users, and a corresponding gateway in the frontend.
- Adds a gateway in the frontend for fetching user data.
- Integrates new gateways with UI.

### CODE REVIEW

**Review by Enkhzul001 — DISMISSED** [review]
Looks good to me

**Review by Enkhzul001 — APPROVED** [review]
looks good

**Review by Lenzs — APPROVED** [review]
everything looks good

**Review by BullDF — APPROVED** [review]
Looking good!

**Review by yuanshu777 — COMMENTED** [review]
Thanks for the hard work!
Looks pretty good

**Pull request merged**
